In [3]:
import numpy as np

## Datatype and Attributes

In [4]:
#making a numpy array
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.6,3.0],
              [9,2.2,7.1]])

a3 = np.array([[[2,5,7],
              [1,3,56],
              [4,6,7]],
             [[10,33,4],
             [4,56,7],
             [11,34,6]]])

In [7]:
a2

array([[1. , 2.6, 3. ],
       [9. , 2.2, 7.1]])

In [8]:
a3

array([[[ 2,  5,  7],
        [ 1,  3, 56],
        [ 4,  6,  7]],

       [[10, 33,  4],
        [ 4, 56,  7],
        [11, 34,  6]]])

In [9]:
a1.shape


(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
#get number of dimensions for a1,a2 and a3
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
#get number of items in array
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
#create a pandas dataframe from a Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.6  3.0
1  9.0  2.2  7.1

## Creating arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
ones = np.ones((2,3))
#returns an ndarray of given shape filled with ones
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
#returns evenly spaced values within a given interval
range_array

array([0, 2, 4, 6, 8])

In [25]:
#create array with random values
random_array = np.random.randint(0,9, size=(3,5))
random_array

array([[8, 2, 6, 4, 1],
       [3, 8, 7, 4, 7],
       [8, 8, 0, 3, 7]])

In [26]:
#another method to create a random array
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.79000241, 0.96507203, 0.32212252],
       [0.76735643, 0.94657449, 0.93080947],
       [0.70768003, 0.57590952, 0.60289974],
       [0.9661417 , 0.51757557, 0.67550374],
       [0.97464507, 0.87146068, 0.44715923]])

In [27]:
#another method to create a rondom array
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.66263363, 0.05996733, 0.81494044],
       [0.76255569, 0.5807114 , 0.32144161],
       [0.28296524, 0.48034392, 0.62856425],
       [0.02259978, 0.64192542, 0.13152755],
       [0.85639704, 0.67986457, 0.69867708]])

## Viewing arrays and matrices

In [28]:
np.unique(random_array_2)

array([0.32212252, 0.44715923, 0.51757557, 0.57590952, 0.60289974,
       0.67550374, 0.70768003, 0.76735643, 0.79000241, 0.87146068,
       0.93080947, 0.94657449, 0.96507203, 0.9661417 , 0.97464507])

In [29]:
a1

array([1, 2, 3])

In [30]:
a2

array([[1. , 2.6, 3. ],
       [9. , 2.2, 7.1]])

In [31]:
a3

array([[[ 2,  5,  7],
        [ 1,  3, 56],
        [ 4,  6,  7]],

       [[10, 33,  4],
        [ 4, 56,  7],
        [11, 34,  6]]])

## Comparing and comparing arrays
### Arithmetic


In [33]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [34]:
a1

array([1, 2, 3])

In [40]:
a2

array([[1. , 2.6, 3. ],
       [9. , 2.2, 7.1]])

In [43]:
a3

array([[[ 2,  5,  7],
        [ 1,  3, 56],
        [ 4,  6,  7]],

       [[10, 33,  4],
        [ 4, 56,  7],
        [11, 34,  6]]])

In [35]:
a1 + ones
#add the elements in the same position of the two arrays

array([2., 3., 4.])

In [36]:
a1 - ones
#subtract the elements in the same position of the two arrays

array([0., 1., 2.])

In [37]:
a1 * ones
#multiplies the elements in the same position of the two arrays

array([1., 2., 3.])

In [38]:
a1 ** 2
#exponents/ raises to the power of 2

array([1, 4, 9], dtype=int32)

In [41]:
np.square(a2)
#find the square

array([[ 1.  ,  6.76,  9.  ],
       [81.  ,  4.84, 50.41]])

In [42]:
np.log(a3)

array([[[0.69314718, 1.60943791, 1.94591015],
        [0.        , 1.09861229, 4.02535169],
        [1.38629436, 1.79175947, 1.94591015]],

       [[2.30258509, 3.49650756, 1.38629436],
        [1.38629436, 4.02535169, 1.94591015],
        [2.39789527, 3.52636052, 1.79175947]]])

### Aggregation
Aggregation = performing the same operation on a number of things

In [45]:
a1

array([1, 2, 3])

Note to use python's method ex `sum()` on python datatypes and
use NumPy'smethods on numpy arrays ex `np.sum()`

In [47]:
#create a large array with 100000 numbers
large_array = np.random.random(100000)
large_array.size

100000

In [48]:
%timeit sum(large_array) #python method
%timeit np.sum(large_array) #numpy method

#numpy is significantly faster than python's method

20.8 ms ± 3.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
129 µs ± 32.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [49]:
np.mean(a1)

2.0

In [50]:
np.max(a1)

3

In [51]:
np.std(a2)
#standard deviation = a measure of how spread out a group of numbers is from the mean
# standard deviation = square root of the variance

2.87735410866766

In [52]:
np.var(a2)
#variance = measure of the average degree to which each number is different to the mean
#higher_variance = Wider range of numbers
#lower variance = lower range of numbers

8.279166666666665

 ## Sorting Arrays`

In [53]:
random_array

array([[8, 2, 6, 4, 1],
       [3, 8, 7, 4, 7],
       [8, 8, 0, 3, 7]])

In [54]:
np.sort(random_array)
#returns thesorted version of an array

array([[1, 2, 4, 6, 8],
       [3, 4, 7, 7, 8],
       [0, 3, 7, 8, 8]])

In [55]:
np.argsort(random_array)
#returns the index of the values in the order they should be numerically

array([[4, 1, 3, 2, 0],
       [0, 3, 2, 4, 1],
       [2, 3, 4, 0, 1]], dtype=int64)

In [56]:
np.argmin(random_array)
#returns the index of the smallest number in the array

12

In [60]:
random_array

array([[8, 2, 6, 4, 1],
       [3, 8, 7, 4, 7],
       [8, 8, 0, 3, 7]])

In [59]:
np.argmax(random_array, axis=0)
#returns the number with the largest number on axis=0 ie columns

array([0, 1, 1, 0, 1], dtype=int64)

In [61]:
np.argmax(random_array, axis=1)
#returns the nimber with the largest number on axis=1 ie rows

array([0, 1, 0], dtype=int64)

## Practical example

<img src="images/panda.png"/>

### Turn the image above into a numpy array

In [67]:
from matplotlib.image import imread

In [68]:
#import the image as a numpy array
panda = imread("images/panda.png")

panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [69]:
panda.size

24465000

In [70]:
panda.ndim

3

<img src="images/car-photo.png"/>

In [72]:
#turning the picture above into a numpy array
car = imread("images/car-photo.png")
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352